# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('super_power', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('display_image', models.ImageField(upload_to='display_picture/')),
            ],
        ),
    ]
